### ISSUE TITLE
motion not working

### ISSUE THREAD

**Issue by Technikte** [djaydev/docker-motioneye#1]
Hi,
it seems like motion can't start in the background so there is no picture.
I am running your docker container on unraid.

```
addgroup: gid '100' in use
ln: /var/log/motion.log: File exists
addgroup: gid '100' in use
ln: /var/log/motion.log: File exists
INFO: hello! this is motionEye server 0.41
ERROR: [Errno 13] Permission denied: '/var/log/motion.log'
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/motioneye/server.py", line 334, in start_motion
motionctl.start()
File "/usr/lib/python2.7/site-packages/motioneye/motionctl.py", line 120, in start
log_file = open(motion_log_path, 'w')
IOError: [Errno 13] Permission denied: '/var/log/motion.log'
INFO: cleanup started
INFO: wsswitch started
INFO: tasks started
INFO: mjpg client garbage collector started
INFO: server started
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
ERROR: motion not running, starting it
ERROR: failed to start motion: [Errno 13] Permission denied: '/var/log/motion.log'
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/motioneye/server.py", line 325, in checker
motionctl.start()
File "/usr/lib/python2.7/site-packages/motioneye/motionctl.py", line 120, in start
log_file = open(motion_log_path, 'w')
IOError: [Errno 13] Permission denied: '/var/log/motion.log'
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
ERROR: motion not running, starting it
ERROR: failed to start motion: [Errno 13] Permission denied: '/var/log/motion.log'
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/motioneye/server.py", line 325, in checker
motionctl.start()
File "/usr/lib/python2.7/site-packages/motioneye/motionctl.py", line 120, in start
log_file = open(motion_log_path, 'w')
IOError: [Errno 13] Permission denied: '/var/log/motion.log'
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 14: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
ERROR: motion not running, starting it
ERROR: failed to start motion: [Errno 13] Permission denied: '/var/log/motion.log'
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/motioneye/server.py", line 325, in checker
motionctl.start()
File "/usr/lib/python2.7/site-packages/motioneye/motionctl.py", line 120, in start
log_file = open(motion_log_path, 'w')
IOError: [Errno 13] Permission denied: '/var/log/motion.log'
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
WARNING: Connect error on fd 13: ECONNREFUSED
```
```
ERROR: failed to start motion: [Errno 13] Permission denied: '/var/log/motion.log'
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/motioneye/server.py", line 325, in checker
motionctl.start()
File "/usr/lib/python2.7/site-packages/motioneye/motionctl.py", line 120, in start
log_file = open(motion_log_path, 'w')
IOError: [Errno 13] Permission denied: '/var/log/motion.log'
ERROR: motion not running, starting it
```

I am not quite sure why permissions get denied.

**Comment by djaydev** [comment]
I'm running it on Unraid as well as a raspberrypi with debian, so far I haven't experienced these logs messages.
What are all the values for volumes and variables did you use the start the container?  For Unraid, they are all in the template .xml so if you're comfortable attach your template file here and I'll take a look.

**Comment by Technikte** [comment]
`run -d --name='motioneye' --net='bridge' --log-opt max-size='50m' --log-opt max-file='1' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'UID'='99' -e 'GID'='100' -p '8765:8765/tcp' -v '/mnt/user/Media/CCTV/':'/var/lib/motioneye':'rw' -v '/mnt/user/appdata/motioneye':'/etc/motioneye':'rw' 'djaydev/motioneye'`

I am using your template via community app. I try to use a foscam c2 rtsp stream camera, if this helps maybe.

**Comment by djaydev** [comment]
Just as a test, change UID to 1000 instead of 99 can paste the logs again.  If you prefer 99 you can change it back after the test.  

I tried your settings by changing my UID to 99 (all my other settings matched yours) and it still worked on my Unraid server.  If it doesn't this time, click the docker icon and then console, and at the prompt type `ls -la /var/log` .

**Comment by djaydev** [comment]
Nevermind, I think I've found the issue.
I'm going to push an update soon that will fix adding network cameras, I'll let you know so you can test it out.

**Comment by djaydev** [comment]
Give it a try when you can.  In Unraid you can upgrade just motioneye with a force update in the docker tab advanced view, or just update all.

**Comment by Technikte** [comment]
Hell yeah, updated the container and added my network camera. Now everything seems to work.
Thanks !
